name: Connect to Server

on: [push]  # Runs on push events (can be customized for other events)

jobs:
  connect:
    runs-on: ubuntu-latest  # Workflow runs on Ubuntu runner

    steps:
      - name: Configure SSH  # Add SSH key and configuration
        run: |
          mkdir -p ~/.ssh  # Create SSH directory if it doesn't exist
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Add private key from secret
          chmod 600 ~/.ssh/id_rsa  # Set permissions on key
          cat >>~/.ssh/config <<EOF  # Configure SSH config
          Host ${{ secrets.HOST }}
            HostName ${{ secrets.HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Reference secret containing private key
          HOST: ${{ secrets.HOST }}  # Reference secret with server hostname
          USER: ${{ secrets.USER }}  # Reference secret with server username
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Run Linux Commands
        run: |
            ssh -T ${{ secrets.HOST }}  /bin/bash <<'EOT'
            echo "These commands will be run on: $( uname -a )"
            echo "They are executed by: $( whoami )"
            EOT
            # cd /www/wwwroot/app.oneworkspace.io/
            # git pull
            # (php artisan down --message 'The app is being (quickly!) updated. Please try again in a minute.') || true

      # - name: Run composer install
      #   run: |
      #     composer install --no-interaction --prefer-dist --optimize-autoloader
      # - name: Run migrations
      #   run: |
      #     php artisan migrate
      #     php artisan optimize

